#!/usr/bin/env python3
"""Remove assets whose links failed the link check from js/data.js.

Reads reports/link-report.json (produced by check_links.py), removes every
asset whose effective link has a non-ok verdict from js/data.js — both the
asset record and its folder references — and appends the removals to
reports/removed-assets.json as an audit trail.

To restore an asset: rebuild js/data.js from the source spreadsheets with
scripts/build_data.py (or re-add it via the admin dashboard), and delete its
entry from reports/removed-assets.json.
"""
import json
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "js" / "data.js"
PREFIX = "window.CSD_DATA = "


def main():
    report = json.loads((ROOT / "reports" / "link-report.json").read_text(encoding="utf-8"))
    raw = DATA.read_text(encoding="utf-8")
    data = json.loads(raw.split(PREFIX, 1)[1].rstrip().rstrip(";"))

    failing_ids = {}
    for row in report["links"]:
        if row["verdict"] != "ok":
            reason = row["verdict"] + (f" (HTTP {row['status']})" if row.get("status") else "")
            for aid in row["assetIds"]:
                failing_ids[aid] = {"reason": reason, "elapsedMs": row["elapsedMs"], "url": row["url"]}

    removed = []
    for aid, info in sorted(failing_ids.items()):
        a = data["assets"].pop(aid, None)
        if a is None:
            continue
        removed.append({
            "id": aid, "title": a.get("title", ""), "url": info["url"],
            "reason": info["reason"], "elapsedMs": info["elapsedMs"],
            "removed": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        })
    for f in data["folders"]:
        f["assetIds"] = [i for i in f["assetIds"] if i not in failing_ids]

    if not removed:
        print("No failing assets present in the catalog — nothing to do.")
        return

    audit_path = ROOT / "reports" / "removed-assets.json"
    audit = json.loads(audit_path.read_text(encoding="utf-8")) if audit_path.exists() else []
    audit.extend(removed)
    audit_path.write_text(json.dumps(audit, indent=1), encoding="utf-8")

    with open(DATA, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/build_data.py — do not edit by hand.\n")
        f.write(PREFIX)
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    print(f"Removed {len(removed)} assets with failing links; "
          f"{len(data['assets'])} assets remain. Audit: {audit_path}")


if __name__ == "__main__":
    main()
