#!/usr/bin/env python3
"""Build js/data.js for the CSD Content Hub from the two source spreadsheets.

Usage:
    python3 build_data.py <CSD_template.xlsx> <Adobe_Assets_Metadata.xlsx>

The CSD template supplies the folder hierarchy (LEVEL 0..7 columns) and the
asset IDs that live in each folder. The metadata workbook supplies, per Celum
Asset ID, the title, description, MWS download URL, content type, size and
literature number. Only those public-facing fields are emitted.
"""
import json
import sys
from pathlib import Path

import openpyxl

LEVEL_COLS = range(3, 11)   # columns D..K  -> LEVEL 0..7
ASSET_START = 14            # column O onwards -> asset IDs
DESCRIPTION_COL = 11        # column L


def parse_template(path):
    ws = openpyxl.load_workbook(path, data_only=True).active
    folders = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row or not row[3]:
            continue
        path_levels = [str(row[i]).strip() for i in LEVEL_COLS
                       if row[i] is not None and str(row[i]).strip()]
        asset_ids = [str(v).strip() for v in row[ASSET_START:]
                     if v is not None and str(v).strip()]
        folders.append({
            "globalId": str(row[0] or "").strip(),
            "cmsId": str(row[2] or "").strip(),
            "path": path_levels,
            "description": str(row[DESCRIPTION_COL]).strip() if row[DESCRIPTION_COL] else "",
            "assetIds": asset_ids,
        })
    return folders


def parse_metadata(path):
    ws = openpyxl.load_workbook(path, read_only=True, data_only=True).active
    rows = ws.iter_rows(values_only=True)
    header = [str(h).strip() if h else "" for h in next(rows)]
    idx = {h: i for i, h in enumerate(header)}

    def cell(row, name):
        v = row[idx[name]]
        return str(v).strip() if v is not None else ""

    assets = {}
    for row in rows:
        if not row or row[idx["Celum Asset ID"]] is None:
            continue
        aid = cell(row, "Celum Asset ID")
        size = row[idx["Size"]]
        assets[aid] = {
            "id": aid,
            "title": cell(row, "Title (English Only)"),
            "description": cell(row, "Description (English Only)"),
            "url": cell(row, "MWS Original File Url"),
            "type": cell(row, "Type"),
            "size": int(size) if isinstance(size, (int, float)) else None,
            "created": cell(row, "Created"),
            "litNumber": cell(row, "Literature Number"),
        }
    return assets


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    template_path, metadata_path = sys.argv[1], sys.argv[2]
    folders = parse_template(template_path)
    assets = parse_metadata(metadata_path)

    used_ids = {a for f in folders for a in f["assetIds"]}
    missing = sorted(used_ids - set(assets))
    if missing:
        print(f"WARNING: {len(missing)} asset IDs in template have no metadata: {missing[:20]}")

    data = {"folders": folders, "assets": assets}
    out = Path(__file__).resolve().parent.parent / "js" / "data.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/build_data.py — do not edit by hand.\n")
        f.write("window.CSD_DATA = ")
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    print(f"Wrote {out}: {len(folders)} folders, {len(assets)} assets "
          f"({len(used_ids)} referenced by folders)")


if __name__ == "__main__":
    main()
